layout_spectrum: 0.1880763431545347
typography_spectrum: 0.9149548793211579
color:
  brandStrength: 0.5553344271611422
  lightness: 0.8222144604660571
  saturation: 0.5015376505907625
  rhythmicContrast: 0.7378052773419768
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
name: dis-ease
